### ISSUE TITLE
Support objects as values: JSON.parse error when getItem() value is Array

### ISSUE THREAD

**Issue by CaitlinWeb** [unadlib/origin-storage#21]
First of all, this is a great library that I want to use for my project. I was already using localForage and needed a way to sync data between domains. 

However, I can't use this because I'm storing arrays and `OriginStorageClient` expects strings for `getItem()`. For example `OriginStorageClient.getItem(key)` fails with a JSON.parse error:
```
Uncaught (in promise) SyntaxError: Unexpected token 'o', "[object Obj"... is not valid JSON
```

[localForage already handles decoding and encoding the value as needed](https://github.com/localForage/localForage/tree/master#storing-blobs-typedarrays-and-other-js-objects). Can this library be updated to remove any changes to values in `getItem()` and `setItem()`? In other words, let localForage handle the values.

**Comment by CaitlinWeb** [comment]
Opened a PR based on my request. I may not have time for revisions but wanted to share a possible solution for anyone else with the same issue.

I'm currently using the fork I created in my project. Now that I'm past the JSON.parse errors, I've noticed another problem. Can open a new issue if you'd prefer.

How this supposed to be used? `onConnect` function is required, so I'm calling that. However since everything is asynchronous there doesn't seem to be way to start getting or setting values from storage. The example in the READMe doesn't even include `onConnect`, or show how to start getting and setting. Wondering if I'm missing something or if this library isn't production-ready...

Since I'm under a timecrunch I'm switching to a different library and implementing the localforage portion myself. But I still think this could be a good, simple solution for others looking for cross-site support with localforage.

**Comment by unadlib** [comment]
hi @CaitlinWeb , I will review your PR as soon as possible.

**Comment by unadlib** [comment]
@CaitlinWeb, v2.1.6 has been released. Thanks for your contribution.

**Comment by CaitlinWeb** [comment]
Thank you, your quick response and merging the PR was much appreciated. I lied about switching to another library; difficult to find something easy to implement that's actively maintained. I much prefer the simple API of origin-storage and how it handles all the heavy lifting. I just need to figure out how to use it properly, but will open a new issue for that.
