### ISSUE TITLE
Why my data saved in origin storage client domain?

### ISSUE THREAD

**Issue by floinay** [unadlib/origin-storage#27]
Hello, i have code on website: https://yeda-crossdomain-storage.web.app/
```
const originStorage = new OriginStorage({
  broadcastChanges: true
});
```

and i have client code: 

```
const client = new OriginStorageClient({
  uri: 'https://yeda-crossdomain-storage.web.app',
  storageOptions: { name: 'yeda_auth' },
});
```

But all saved data stored on my client domain.
Storage website data always empty.

**Comment by unadlib** [comment]
hi @floinay, you must set a valid `targetOrigin` in OriginStorage. For example,

```ts
import { OriginStorage } from 'origin-storage';

const originStorage = new OriginStorage({
  broadcastChanges: true,
  targetOrigin: 'http://127.0.0.1:8080/',
});
```

**Comment by unadlib** [comment]
it may be a cross-domain storage issues, I'm testing in the current repo's example without any issues.

**Comment by floinay** [comment]
any idea what is wrong with my storage?

**Comment by floinay** [comment]
I checked, yes is third party, but each domain has only self data
<img width="800" alt="image" src="https://github.com/unadlib/origin-storage/assets/19957549/6c38f5fe-a38d-4fd5-b74b-a95afb31d18d">
Domain 1: 
![image](https://github.com/unadlib/origin-storage/assets/19957549/7d82888d-1b5f-47c1-b894-09674d062964)

Domain 2:
![image](https://github.com/unadlib/origin-storage/assets/19957549/cb46f383-33b6-4bc1-b0bd-dcbc8f5e005e)

**Comment by floinay** [comment]
i just realized that it only works if the domains are open in the browser at the same time

**Comment by floinay** [comment]
i just realized that it only works if the domains are open in the browser at the same time
